# Generated by Django 2.0.2 on 2018-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180210_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_veteran',
            field=models.BooleanField(default=False),
        ),
    ]
