# Generated by Django 2.0.2 on 2018-02-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180210_1937'),
        ('account', '0020_auto_20180210_2109'),
    ]

    operations = [
    ]
