# Generated by Django 2.0.2 on 2018-02-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_merge_20180210_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_veteran',
            field=models.BooleanField(default=False),
        ),
    ]
